/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory.management.system;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class HomePage extends javax.swing.JFrame
{
    JPanel mainPanel;
    SuperAdminLogin s;
    String id;
    /**
     * Creates new form HomePage
     */
    public HomePage(SuperAdminLogin s)
    {
        initComponents();
        setLocationRelativeTo(null);
        this.s = s;
        CommonConnection.addImage(lblclose, "D:\\Inventory Management System Images & Icon\\images\\close.png");
        CommonConnection.addImage(lblview1, "D:\\Inventory Management System Images & Icon\\images\\logout.png");
        CardLayout cardlayout = new CardLayout();
        mainPanel = new JPanel(cardlayout);
        mainPanel.setBounds(6,100, 1265,650);
        mainPanel.setBackground(new Color(204,204,255));
        jPanel1.add(mainPanel);
        mainPanel.add(userpanel);
        lblheading.setText("MANAGE USER");
        displayTable("user", jTable1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        userpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtphoneno2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtlocaladd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        cmbstatus = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblclose = new javax.swing.JLabel();
        lblheading = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbluser8 = new javax.swing.JLabel();
        lblview1 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Name", "Mobile no.", "Email", "Address", "Status"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        jLabel3.setText("Name:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtfname.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        txtfname.setText(" ");
        txtfname.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                txtfnameMouseClicked(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtfnameActionPerformed(evt);
            }
        });
        txtfname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtfnameKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        jLabel1.setText("Phone No.:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtphoneno2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        txtphoneno2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtphoneno2ActionPerformed(evt);
            }
        });
        txtphoneno2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtphoneno2KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        jLabel2.setText("Email Id:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtemail.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtemailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        jLabel6.setText("Address:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtlocaladd.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        txtlocaladd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtlocaladdActionPerformed(evt);
            }
        });
        txtlocaladd.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtlocaladdKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        jLabel7.setText("Password:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        jLabel8.setText("Status:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpassword.setToolTipText("Enter your password here");
        txtpassword.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtpasswordActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 0, 0));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsaveActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(0, 0, 0));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncloseActionPerformed(evt);
            }
        });

        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", " " }));

        btnupdate.setBackground(new java.awt.Color(0, 0, 0));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.setEnabled(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnupdateActionPerformed(evt);
            }
        });

        btnupdate1.setBackground(new java.awt.Color(0, 0, 0));
        btnupdate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnupdate1.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate1.setText("Reset");
        btnupdate1.setEnabled(false);
        btnupdate1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnupdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphoneno2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlocaladd, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnupdate)
                                    .addComponent(cmbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addComponent(btnupdate1)
                                .addGap(56, 56, 56)
                                .addComponent(btnclose)))
                        .addGap(48, 48, 48))
                    .addComponent(btnsave)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1))
                            .addComponent(txtphoneno2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlocaladd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userpanelLayout = new javax.swing.GroupLayout(userpanel);
        userpanel.setLayout(userpanelLayout);
        userpanelLayout.setHorizontalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userpanelLayout.setVerticalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1277, 800));
        jPanel1.setRequestFocusEnabled(false);

        lblclose.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblcloseMouseClicked(evt);
            }
        });

        lblheading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblheading.setIconTextGap(3);
        lblheading.setInheritsPopupMenu(false);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jPanel11MouseExited(evt);
            }
        });

        lbluser8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lbluser8.setText("Logout");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblview1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbluser8)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbluser8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblview1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblheading, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addGap(172, 172, 172)
                .addComponent(lblclose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblclose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(724, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblcloseMouseClicked
    {//GEN-HEADEREND:event_lblcloseMouseClicked
        if(JOptionPane.showConfirmDialog(this, "Do you really want to exit?") == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_lblcloseMouseClicked

    private void txtfnameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtfnameMouseClicked
    {//GEN-HEADEREND:event_txtfnameMouseClicked
        txtfname.setFont(new Font("Times New Roman",Font.BOLD,20));
    }//GEN-LAST:event_txtfnameMouseClicked

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtfnameActionPerformed
    {//GEN-HEADEREND:event_txtfnameActionPerformed

    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtfnameKeyTyped
    {//GEN-HEADEREND:event_txtfnameKeyTyped
        char ch = evt.getKeyChar();
        if(!Character.isAlphabetic(ch))
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtfnameKeyTyped

    private void txtphoneno2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtphoneno2ActionPerformed
    {//GEN-HEADEREND:event_txtphoneno2ActionPerformed
        if(txtphoneno2.getText().length() != 10)
        {
            JOptionPane.showMessageDialog(this,"Invalid Mobile Number!");
            txtphoneno2.setText(null);
        }
    }//GEN-LAST:event_txtphoneno2ActionPerformed

    private void txtphoneno2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtphoneno2KeyTyped
    {//GEN-HEADEREND:event_txtphoneno2KeyTyped
        char ch = evt.getKeyChar();
        if(!Character.isDigit(ch))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtphoneno2KeyTyped

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtemailActionPerformed
    {//GEN-HEADEREND:event_txtemailActionPerformed
        String email = txtemail.getText();
        if(email == null|| email.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter email!");
        }
        else
        {

            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+"[a-zA-Z0-9_+&*-]+)*@"+"(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            Pattern pattern = Pattern.compile(emailRegex);
            if(!pattern.matcher(email).matches())
            {
                JOptionPane.showMessageDialog(this,"Inavlid email");
            }
        }

    }//GEN-LAST:event_txtemailActionPerformed

    private void txtlocaladdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtlocaladdActionPerformed
    {//GEN-HEADEREND:event_txtlocaladdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocaladdActionPerformed

    private void txtlocaladdKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtlocaladdKeyTyped
    {//GEN-HEADEREND:event_txtlocaladdKeyTyped
        //        char ch = evt.getKeyChar();
        //        if(!(Character.isAlphabetic(ch) || ch != ' '))
        //
        {
            //            evt.consume();
            //        
    }
    }//GEN-LAST:event_txtlocaladdKeyTyped
    
   public void displayTable(String tableName, JTable table) {
    try {
        Connection con = CommonConnection.getConnection();
        String query = "SELECT * FROM " + tableName;
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();

        // Get metadata to dynamically get column names and count
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();

        // Get column names
        Vector<String> columnNames = new Vector<>();
        for (int i = 1; i <= columnCount; i++) {
            columnNames.add(rsmd.getColumnName(i));
        }

        // Get rows data
        Vector<Vector<Object>> rows = new Vector<>();
        while (rs.next()) {
            Vector<Object> row = new Vector<>();
            for (int i = 1; i <= columnCount; i++) {
                row.add(rs.getObject(i));
            }
            rows.add(row);
        }

        // Update the JTable model with the new data
        DefaultTableModel model = new DefaultTableModel(rows, columnNames);
        table.setModel(model);

    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsaveActionPerformed
    {//GEN-HEADEREND:event_btnsaveActionPerformed
       try
        {
            Connection con = CommonConnection.getConnection();
            String query = "Insert into user(`Name`, `Mobile_no`, `Email`, `Password`, `Address`, `Status`) values (?,?,?,?,?,?);";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1,txtfname.getText());
            pst.setString(2,txtphoneno2.getText());
            pst.setString(3,txtemail.getText());
            pst.setString(4,String.valueOf(txtpassword.getPassword()));
            pst.setString(5,txtlocaladd.getText());
            pst.setString(6,String.valueOf(cmbstatus.getSelectedItem()));
            if(txtfname.getText().equals("") && txtphoneno2.getText().equals("") && txtemail.getText().equals("") && String.valueOf(txtpassword.getPassword()).equals(""))
            {
                JOptionPane.showMessageDialog(this,"Fill all the fields!");
            }
            else
            {
                pst.executeUpdate();
            }
            
            displayTable(jTable1.getName(), jTable1);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncloseActionPerformed
    {//GEN-HEADEREND:event_btncloseActionPerformed
        new SuperAdminLogin().setVisible(true);
        this.dispose();
        
       
    }//GEN-LAST:event_btncloseActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
       int r= jTable1.getSelectedRow();
       id = jTable1.getValueAt(r, 0).toString();
       txtfname.setText(jTable1.getValueAt(r, 1).toString());
       txtphoneno2.setText(jTable1.getValueAt(r, 2).toString());
       txtemail.setText(jTable1.getValueAt(r, 3).toString());
       txtlocaladd.setText(jTable1.getValueAt(r, 5).toString());
       cmbstatus.setSelectedItem(jTable1.getValueAt(r,6).toString());
       btnsave.setEnabled(false);
       btnupdate.setEnabled(true);
       btnupdate1.setEnabled(true);
       txtpassword.setEnabled(false);
       txtemail.setEnabled(false);
       txtlocaladd.setEnabled(false);
       txtphoneno2.setEnabled(false);
       txtfname.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnupdateActionPerformed
    {//GEN-HEADEREND:event_btnupdateActionPerformed
        try
        {
            Connection con = CommonConnection.getConnection();
            String query = "update user set `Name` = ?, `Mobile_no` = ?, `Email` = ?, `Address` = ?, `Status` = ? where `id` = ?;";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1,txtfname.getText());
            pst.setString(2,txtphoneno2.getText());
            pst.setString(3,txtemail.getText());
            pst.setString(4,txtlocaladd.getText());
            pst.setString(5,String.valueOf(cmbstatus.getSelectedItem()));
            pst.setString(6,id);
            pst.executeUpdate();
            txtfname.setText(null);
            txtphoneno2.setText(null);
            txtemail.setText(null);
            txtpassword.setText(null);
            txtlocaladd.setText(null);
            displayTable("user", jTable1);
            btnsave.setEnabled(true);
            btnupdate.setEnabled(false);
            btnupdate1.setEnabled(false);
             txtpassword.setEnabled(true);
            txtemail.setEnabled(true);
            txtlocaladd.setEnabled(true);
            txtphoneno2.setEnabled(true);
            txtfname.setEnabled(true);
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnupdate1ActionPerformed
    {//GEN-HEADEREND:event_btnupdate1ActionPerformed
       displayTable("user", jTable1);
       txtfname.setText(null);
       txtphoneno2.setText(null);
       txtemail.setText(null);
       txtpassword.setText(null);
       txtlocaladd.setText(null);
       cmbstatus.setSelectedItem("Active");
       displayTable("user", jTable1);
       btnsave.setEnabled(true);
       btnupdate.setEnabled(false);
       btnupdate1.setEnabled(false);
       txtpassword.setEnabled(true);
       txtemail.setEnabled(true);
       txtlocaladd.setEnabled(true);
       txtphoneno2.setEnabled(true);
       txtfname.setEnabled(true);
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtpasswordActionPerformed
    {//GEN-HEADEREND:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel11MouseExited
    {//GEN-HEADEREND:event_jPanel11MouseExited
        jPanel11.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel11MouseEntered
    {//GEN-HEADEREND:event_jPanel11MouseEntered
        jPanel11.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel11MouseClicked
    {//GEN-HEADEREND:event_jPanel11MouseClicked
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblheading;
    private javax.swing.JLabel lbluser8;
    private javax.swing.JLabel lblview1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlocaladd;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphoneno2;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
